services:
  odoo:
    container_name: ${COMPOSE_PROJECT_NAME}_odoo
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ..:/workspace
      # - ../odools.toml:/home/odoo/.config/odools.toml:ro
      - ${ODOO_BASE}:/workspace/odoo:ro
      - ${ENTERPRISE_ADDONS}:/workspace/enterprise:ro
      - odoo-data:/var/lib/odoo
      - ${HOME}/.local/share/opencode:/home/odoo/.local/share/opencode
      - ${HOME}/.config/opencode:/home/odoo/.config/opencode
    command: sleep infinity
    # command: odoo --dev=all
    ports:
      - "8069:8069"
      - "8071:8071"
      - "8072:8072"
    networks:
      - internal
      # - shared-net

  pgdb:
    image: pgvector/pgvector:pg18
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME}_pgdb
    volumes:
      # For PostgreSQL 18+ we mount the parent dir so the versioned cluster
      # layout (/var/lib/postgresql/18/main) can be created correctly.
      - pgdb-data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - internal
     # - shared-net

volumes:
  odoo-data:
  pgdb-data:
  pgadmin-data:

networks:
  internal:
    driver: bridge
  shared-net:
    external: true
    name: shared-net

